name: Automated test

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: jupyter-output-monitor
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Set up dependencies
        run: pip install .
      - name: Initialize playwright
        run: playwright install
      - name: Run monitoring command
        run: jupyter-output-monitor --notebook automated/imviz-profile.ipynb --headless
